name: Rust

on: push

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Check for errors
        # here we check the neutron-proto crate is wasm-compatible when the grpc-
        # related features are turned off
        # we also do not check tests since they use the grpc features
        run: cargo check --locked --target wasm32-unknown-unknown -p neutron-proto --no-default-features --features cosmwasm
        env:
          RUST_BACKTRACE: 1

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Run tests
        run: cargo test -p neutron-proto --all-features
        env:
          RUST_BACKTRACE: 1

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy

      - name: Run clippy
        # here we only check for linter warnings in the proto-build crate.
        # the generated prost code may contain some warnings but that's not our fault
        run: cargo clippy -p proto-build -- -D warnings
